export const data = [
  {
    _id: "62c97224c2e3ddfac8d8f22a",
    name: "Ozodbek",
    surename: "Musoeyv",
    father_name: "Oatbek o'g'li",
    phone_number: "994528673",
    passport_seria_number: "AA2615484",
    passport_jshir: "74474848484",
    passport_location: "ddddddd",
    birth_date: "2022-07-20 17:17:49",
    gender: "male",
    region: "Buhoro",
    city: "Buhoro|Buhoro",
    street: "eeeeeee",
    home_number: "9999999999999999999",
    bio_img:
      "http://localhost:4000/ariza\\08c9ab501183cd17184ded7d72fd881e.jpg",
    finished_study: "dwedwedwe",
    country: "Беларусь Республикаси",
    university: "Полоцк давлат университети",
    study_type: "morning",
    study_lang: "rus",
    study_level: "bachelor",
    facultet: "Funksional ovqatlanish va bolalar maxsulotlari texnologiyasi",
    __v: 0,
  },
  {
    _id: "62ca02c9f99027b0132e3c77",
    name: "Ziyodulla",
    surename: "Sodiqov",
    father_name: "Mehriddin ogli",
    phone_number: "930731445",
    passport_seria_number: "sndfjsdn skfds",
    passport_jshir: "sdfnsjdf ksfskfs",
    passport_location: "sjndfj",
    birth_date: "2022-07-12 23:34:52",
    gender: "male",
    region: "Buhoro",
    city: "Buhoro|Buhoro",
    street: "dfgd",
    home_number: "23",
    bio_img:
      "http://localhost:4000/ariza\\b16a3e585e3452a1b1547a78a4b997b5.PNG",
    finished_study: "wef",
    country: "Беларусь Республикаси",
    university: "Белоруссия давлат технологоия университети",
    study_type: "evening",
    study_lang: "rus",
    study_level: "bachelor",
    facultet: "Kimyoviy texnologiya (ishlab chiqarish turlari boʼyicha)",
    __v: 0,
  },
  {
    _id: "62ca9129ed7a46f21dbdcb30",
    name: "Shohruh ",
    surename: "Abdullayev",
    father_name: "Rustamovich",
    phone_number: "88943155666",
    passport_seria_number: "AA2554379",
    passport_jshir: "3030777911005478",
    passport_location: "Gurlan IIB",
    birth_date: "1997-07-03 13:41:03",
    gender: "male",
    region: "Toshkent",
    city: "Turkiston",
    street: "Tashkent",
    home_number: "942335666",
    bio_img:
      "http://localhost:4000/ariza\\b3b62f58d46866912e8487f3f42ab858.JPG",
    finished_study: "TaTU",
    country: "Беларусь Республикаси",
    university: "Латвия табиий фанлар ва технология университети",
    study_type: "morning",
    study_lang: "rus",
    study_level: "bachelor",
    facultet: "Neftь va neftь-gazni qayta ishlash texnologiyasi",
    __v: 0,
  },
  {
    _id: "62cacde215e1f11a682fa15a",
    name: "Ziyodulla",
    surename: "Sodiqov",
    father_name: "Mehriddin ogli",
    phone_number: "930731445",
    passport_seria_number: "sndfjsdn skfds",
    passport_jshir: "sdfnsjdf ksfskfs",
    passport_location: "sjndfj",
    birth_date: "2022-07-22 14:00:24",
    gender: "male",
    region: "Samarqand",
    city: "Bulung`ur|Bulung`ur",
    street: "jahfnsdkfsfk",
    home_number: "23",
    bio_img:
      "http://localhost:4000/ariza\\65a7dce54adbf01c3f121056c69ca549.PNG",
    finished_study: "wererw",
    country: "Беларусь Республикаси",
    university: "Белоруссия давлат технологоия университети",
    study_type: "evening",
    study_lang: "rus",
    study_level: "bachelor",
    facultet:
      "Texnologik jarayonlar va ishlab chiqarishni avtomatlashtirish va boshqarish (tarmoqlar boʼyicha)",
    __v: 0,
  },
  {
    _id: "62caded815e1f11a682fa162",
    name: "Ziyodulla",
    surename: "Sodiqov",
    father_name: "Mehriddin ogli",
    phone_number: "930731445",
    passport_seria_number: "sndfjsdn skfds",
    passport_jshir: "sdfnsjdf ksfskfs",
    passport_location: "sjndfj",
    birth_date: "2022-07-27 15:13:55",
    gender: "male",
    region: "Buhoro",
    city: "Galaosiyo|Galaosiyo",
    street: "jahfnsdkfsfk",
    home_number: "23",
    bio_img:
      "http://localhost:4000/ariza\\754eb4224638e35a98e04f475debfa72.PNG",
    finished_study: "wererw",
    country: "Беларусь Республикаси",
    university:
      "Белоруссия давлат озик-овкат ва кимёвий технологоиялар университети",
    study_type: "morning",
    study_lang: "rus",
    study_level: "bachelor",
    facultet:
      "Texnologik mashinalar va jihozlar (sovutish, kriogen texnikasi va moʼtadillash tizimlari mashinalari hamda agregatlari)",
    __v: 0,
  },
];
